language: d
d:
  - dmd-2.066.1
  - ldc-0.15.1
install:
  - sudo wget http://netcologne.dl.sourceforge.net/project/d-apt/files/d-apt.list -O/etc/apt/sources.list.d/d-apt.list;
  - sudo apt-get update;
  - sudo apt-get -y --allow-unauthenticated install --reinstall d-apt-keyring;
  - sudo apt-get update;
  - sudo apt-get install dmd-bin dub 
  - sudo dub fetch tested
  - sudo dub fetch doveralls
  # Install new dub
  - git clone https://github.com/D-Programming-Language/dub
  - cd dub && dub build
  - cd ..
script: sudo ./dub/bin/dub test -q --coverage
after_success: sudo dub run doveralls -- -p `pwd` -j $TRAVIS_JOB_ID
